#!/usr/bin/env sh

SLOC1=$(cloc --json ./src/Game/* | jq '.Haskell.code')
badge sloc "$SLOC1" :blue .svg > ./misc/generated/sloc-game.svg

SLOC2=$(( $(cloc --json ./src | jq '.Haskell.code') - $SLOC1 ))
badge sloc "$SLOC2" :blue .svg > ./misc/generated/sloc-ui.svg

SLOC3=$(cloc --json ./json-relay/src ./json-relay/Main.hs | jq '.Haskell.code')
badge sloc "$SLOC3" :blue .svg > ./misc/generated/sloc-json-relay.svg
