#!/usr/bin/env sh

# Run from json-relay

stack image container
docker save json-relay > /tmp/json-relay.tar
scp ./docker-compose.yaml root@relay.ianjeffries.net:/root
scp /tmp/json-relay.tar root@relay.ianjeffries.net:/root
