name: json-relay
default-extensions:

  # Notable

  - NoImplicitPrelude

  # Other

  - DataKinds
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - ExistentialQuantification
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - ScopedTypeVariables
  - TypeFamilies
  - TypeOperators

ghc-options: -Wall
dependencies:

  # Notable

  - network
  - streaming

  # Other

  - aeson
  - async
  - base
  - bytestring
  - containers
  - directory
  - filepath
  - hashable
  - lens
  - monad-loops
  - mtl
  - random
  - safe-exceptions
  - stm
  - text
  - time
  - transformers
  - unordered-containers

library:
  source-dirs: src
executables:
  json-relay:
    source-dirs: ./
    main: Main.hs
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      - gitrev
      - json-relay
      - optparse-applicative
tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - json-relay
